### ISSUE TITLE
Sample Build Configuration

### ISSUE THREAD

**Issue by BlackFrog1** [JetBrains/teamcity-dotnet-samples#1]
The link from the blog post (https://blog.jetbrains.com/teamcity/2020/12/teamcity-integration-with-net-part-1-new-approach-and-demo/)  showing the same build configuration for new .NET Runner includes a link to the demo build configuration.  [Demo Team City Server](https://teamcity.jetbrains.com/project.html?projectId=DemoProjects_TeamCity_Net&_gl=1*1mlhxyw*_ga*MTYyNDQ0ODE5Mi4xNjA5MjczNjI0*_ga_0WQ2ZF5VGT*MTYzMDY5MTM2Mi4xLjEuMTYzMDY5MTg5NC42MA..&_ga=2.46758375.1531372088.1630691362-1624448192.1609273624) is not there any longer.  Can you please add the actual build configuration to github repo.  

Thanks.

**Comment by NikolayPianikov** [comment]
@BlackFrog1 Looks like some NET troubles, it is accessible from Germany and Netherlands but inaccessible from Russia, for instance. Will investigate.

**Comment by NikolayPianikov** [comment]
@BlackFrog1 could you check https://teamcity.jetbrains.com/project.html?projectId=DemoProjects_TeamCity_Net

**Comment by NikolayPianikov** [comment]
Fixed
